### ISSUE TITLE
Cancel button does not work

### ISSUE THREAD

**Issue by BeJoNe** [nuitsjp/HyperV-Switch#3]
v1.0.1 - the cancel button does nothing, I have to use X top-right

**Comment by nuitsjp** [comment]
I'd forgotten...
Thanks for the reminder.
Please be patient.

**Comment by nuitsjp** [comment]
I fixed it and released it.
Thank you for your contribution!

https://github.com/nuitsjp/HyperV-Switch/releases/tag/v1.0.2
